### ISSUE TITLE
Bug: "x-powered-by" in lowercase is not removed

### ISSUE THREAD

**Issue by ddsultan** [helmetjs/hide-powered-by#4]
**Actual**: Response Header with `x-powered-by: PHP 7.1` (all lowercase) is not being removed 

**Expected**: Response Header with `x-powered-by: PHP 7.1` (all lowercase) is removed

**Comment by EvanHahn** [comment]
Could you send a code snippet that demonstrates your problem?

**Comment by ddsultan** [comment]
https://github.com/helmetjs/hide-powered-by/blob/e7b2c68f53c4611b6db65afaa27b93a7217d5195/index.ts#L17

**Comment by EvanHahn** [comment]
Ah, sorry, I was unclear. Could you send some sample code that demonstrates this?

For example, I'm not able to reproduce this problem when I run the following app:

```js
const express = require('express')
const hidePoweredBy = require('hide-powered-by')

const app = express()

app.use((req, res, next) => {
  res.setHeader('X-Powered-By', 'this should be removed')
  next()
})

app.use(hidePoweredBy())

app.get('/', (req, res) => {
  res.send('Hello world!')
})

app.listen(3000)
```

**Comment by ddsultan** [comment]
This is the code example to reproduce the issue:

```js
const express = require('express')
const hidePoweredBy = require('hide-powered-by')

const app = express()

app.use((req, res, next) => {
  res.setHeader('X-Powered-By', 'this should be removed')
  next()
})

app.use(hidePoweredBy())

app.get('/', (req, res) => {
  res.setHeader('x-powered-by', 'this is not removed')
  res.send('Hello world!')
})

app.listen(3000)
```

**Comment by EvanHahn** [comment]
This is working as expected. `hide-powered-by` should remove the `X-Powered-By` header if set earlier in the request handler stack, but it doesn't prevent it from being added later (like in your code sample above).
